name: Node.js CI and Deploy

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm install
      - run: npm run build --if-present

      # Only run deployment on Node.js 18.x to avoid multiple deployments
      - name: Deploy to GitHub Pages
        if: matrix.node-version == '18.x' && github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist
          clean: true

      # Copy CNAME file to dist folder
      - name: Copy CNAME file
        if: matrix.node-version == '18.x' && github.ref == 'refs/heads/main'
        run: |
          cp assets/CNAME dist/CNAME

      # Optional: Add custom domain configuration
      - name: Configure custom domain
        if: matrix.node-version == '18.x' && github.ref == 'refs/heads/main'
        uses: actions/configure-pages@v3
        with:
          enablement: true
          custom_domain: agitimeline.org

permissions:
  contents: write
  pages: write
